version: '2.0'
workflow:
  tasks:
    CFT_Training_Workflow_Weekly_Users_12927614:
      action: civis.run_job
      input:
        job_id: 12927614
      on-success:
        - 02_Scoring_Workflow
    02_Scoring_Workflow:
      action: civis.run_job
      input:
        job_id: 12927662
      on-success:
        - 03_Activation_Workflow 
    03_Activation_Workflow:
      action: civis.run_job
      input:
        job_id: 12927672
